[project]
name = "251121-langchain-study"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-anthropic>=1.1.0",
    "langchain-openai>=1.0.3",
    "langgraph>=1.0.3",
    "prompt-toolkit>=3.0.52",
    "pydantic-settings>=2.12.0",
    "rich>=14.2.0",
]

[tool.uv.workspace]
members = [
    "apps/app1",
    "apps/app2",
    "apps/app3",
    "apps/app4",
    "apps/app5",
]
