[project]
name = "04-chainlit-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["m_utils"]

[tool.uv.sources]
m_utils = { workspace = true }
